name: Deploy

on:
  push:
    branches:
      - "*"
      - "!skipci*"

concurrency:
  group: ${{ startsWith(github.ref_name, 'snyk-') && 'snyk' || github.ref_name }}-group

env:
  STAGE_NAME: ${{ startsWith(github.ref_name, 'snyk-') && 'snyk' || github.ref_name }}

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ startsWith(github.ref_name, 'snyk-') && 'snyk' || github.ref_name }}
    outputs:
      app-url: ${{ steps.deployment-data.outputs.APPURL }}
      kibana-url: ${{ steps.deployment-data.outputs.KIBANAURL }}
    steps:
      - name: Set Application URLs
        id: deployment-data
        run: |

          echo "APPURL=asdfasdfasdf" >> $GITHUB_OUTPUT

  application-url:
    runs-on: ubuntu-20.04
    needs:
      - deploy
    environment:
      name: ${{ startsWith(github.ref_name, 'snyk-') && 'snyk' || github.ref_name }}-app
      url: ${{ needs.deploy.outputs.app-url }}
    steps:
      - name: Display App URL
        run: |
          echo "App URL: ${{ needs.deploy.outputs.app-url }}"
      - name: Write url to file
        run: echo "${{ needs.deploy.outputs.app-url }}" > app-url.txt
      - name: Upload App URL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-url
          path: app-url.txt
